# docker/matrix/configs/bot-03/slack.yaml
# Bot-03 - Software engineer bot
# Inherits from: ./base/slack.yaml

inherits: ./base/slack.yaml

security:
  permission:
    bot_user_id: U0AL7H8UU75
    broadcast_response: ""
